services:
  - type: web
    name: budgetpal-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    branch: main

  - type: pserv
    name: budgetpal-database
    env: postgresql
    plan: free
    databaseName: budgetpal
    databaseUser: budgetpal_user
